GET http://localhost:5299/$odata
###

GET http://localhost:5299/default
###

GET http://localhost:5299/default/Customers
###

POST http://localhost:5299/default/$batch
Content-Type: application/json

{
  "requests": [
    {
      "id": "1",
      "method": "GET",
      "url": "Customers"
    },
    {
      "id": "2",
      "method": "GET",
      "url": "Customers"
    },
    {
      "id": "3",
      "method": "GET",
      "url": "Customers"
    }
  ]
}
###
